module.exports = {
  FETCH_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS_SUCCESS',
  FETCH_TRANSACTIONS_ERROR: 'FETCH_TRANSACTIONS_ERROR',

  FETCH_CHART_TRANSACTIONS_SUCCESS: 'FETCH_CHART_TRANSACTIONS_SUCCESS',
  FETCH_CHART_TRANSACTIONS_ERROR: 'FETCH_CHART_TRANSACTIONS_ERROR',

  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',

  CHANGE_TRANSACTION_CATEGORY_SUCCESS: 'CHANGE_TRANSACTION_CATEGORY_SUCCESS',
  CHANGE_TRANSACTION_CATEGORY_ERROR: 'CHANGE_TRANSACTION_CATEGORY_ERROR',

  CHANGE_DATE_RANGE: 'CHANGE_DATE_RANGE',
  CHANGE_TABLE_FILTER: 'CHANGE_TABLE_FILTER',

  FETCH_NET_INCOME_SUCCESS: 'FETCH_NET_INCOME_SUCCESS',
  FETCH_NET_INCOME_ERROR: 'FETCH_NET_INCOME_ERROR',

  FETCH_NET_WORTH_SUCCESS: 'FETCH_NET_WORTH_SUCCESS',
  FETCH_NET_WORTH_ERROR: 'FETCH_NET_WORTH_ERROR',

  FETCH_BANK_ASSETS_SUCCESS: 'FETCH_BANK_ASSETS_SUCCESS',
  FETCH_BANK_ASSETS_ERROR: 'FETCH_BANK_ASSETS_ERROR'
};
