module.exports = {
  FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
  FETCH_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS_SUCCESS',
  FETCH_TRANSACTIONS_ERROR: 'FETCH_TRANSACTIONS_ERROR',
  FETCH_CHART_TRANSACTIONS: 'FETCH_TRANSACTIONS',
  FETCH_CHART_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS_SUCCESS',
  FETCH_CHART_TRANSACTIONS_ERROR: 'FETCH_TRANSACTIONS_ERROR',
  CHANGE_DATE_RANGE: 'CHANGE_DATE_RANGE'
};
