module.exports = {
  FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
  FETCH_CHART_TRANSACTIONS: 'FETCH_CHART_TRANSACTIONS',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  CHANGE_TRANSACTION_CATEGORY: 'CHANGE_TRANSACTION_CATEGORY',
  FETCH_NET_INCOME: 'FETCH_NET_INCOME',
  FETCH_NET_WORTH: 'FETCH_NET_WORTH',
  FETCH_BANK_ASSETS: 'FETCH_BANK_ASSETS',
  FETCH_ACCOUNTS: 'FETCH_ACCOUNTS',
};
